//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GoTextTemplateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGoTextTemplateParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] GoTextTemplateParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] GoTextTemplateParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] GoTextTemplateParser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] GoTextTemplateParser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPart([NotNull] GoTextTemplateParser.PartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPart([NotNull] GoTextTemplateParser.PartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlaceholder([NotNull] GoTextTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlaceholder([NotNull] GoTextTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] GoTextTemplateParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] GoTextTemplateParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForBlock([NotNull] GoTextTemplateParser.ForBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForBlock([NotNull] GoTextTemplateParser.ForBlockContext context);
}
