//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TextTemplate/SimpleTemplateParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SimpleTemplateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISimpleTemplateParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] SimpleTemplateParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] SimpleTemplateParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPart([NotNull] SimpleTemplateParser.PartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPart([NotNull] SimpleTemplateParser.PartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlaceholder([NotNull] SimpleTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlaceholder([NotNull] SimpleTemplateParser.PlaceholderContext context);
}
