//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TextTemplate {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class GoTextTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN_TRIM=1, OPEN=2, TEXT=3, CLOSE_TRIM=4, CLOSE=5, IF=6, ELSE=7, END=8, 
		FOR=9, RANGE=10, IN=11, COLONEQ=12, COMMA=13, DOLLAR=14, DOT=15, LBRACK=16, 
		RBRACK=17, NUMBER=18, STRING=19, BOOLEAN=20, EQ=21, NE=22, LT=23, LE=24, 
		GT=25, GE=26, AND=27, OR=28, NOT=29, IDENT=30, COMMENT=31, WS=32;
	public const int
		EXPR=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "EXPR"
	};

	public static readonly string[] ruleNames = {
		"OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", "END", 
		"FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "DOT", "LBRACK", "RBRACK", 
		"NUMBER", "STRING", "BOOLEAN", "EQ", "NE", "LT", "LE", "GT", "GE", "AND", 
		"OR", "NOT", "IDENT", "COMMENT", "WS"
	};


	public GoTextTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GoTextTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{{-'", "'{{'", null, "'-}}'", "'}}'", "'if'", "'else'", "'end'", 
		"'for'", "'range'", "'in'", "':='", "','", "'$'", "'.'", "'['", "']'", 
		null, null, null, "'eq'", "'ne'", "'lt'", "'le'", "'gt'", "'ge'", "'and'", 
		"'or'", "'not'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", 
		"END", "FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "DOT", "LBRACK", 
		"RBRACK", "NUMBER", "STRING", "BOOLEAN", "EQ", "NE", "LT", "LE", "GT", 
		"GE", "AND", "OR", "NOT", "IDENT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GoTextTemplateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GoTextTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\"', '\xDB', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x4', '\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', 
		'\x18', '\t', '\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', 
		'\x1A', '\x4', '\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', 
		'\x1D', '\t', '\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', 
		'\x1F', '\x4', ' ', '\t', ' ', '\x4', '!', '\t', '!', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x6', '\x4', 'S', '\n', '\x4', '\r', 
		'\x4', '\xE', '\x4', 'T', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x6', '\x13', '\x89', 
		'\n', '\x13', '\r', '\x13', '\xE', '\x13', '\x8A', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\x91', '\n', '\x14', 
		'\f', '\x14', '\xE', '\x14', '\x94', '\v', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', 
		'\x15', '\xA1', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xC2', '\n', 
		'\x1F', '\f', '\x1F', '\xE', '\x1F', '\xC5', '\v', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\a', ' ', '\xCB', '\n', ' ', '\f', 
		' ', '\xE', ' ', '\xCE', '\v', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', '!', '\x6', '!', '\xD6', '\n', '!', '\r', 
		'!', '\xE', '!', '\xD7', '\x3', '!', '\x3', '!', '\x3', '\xCC', '\x2', 
		'\"', '\x4', '\x3', '\x6', '\x4', '\b', '\x5', '\n', '\x6', '\f', '\a', 
		'\xE', '\b', '\x10', '\t', '\x12', '\n', '\x14', '\v', '\x16', '\f', '\x18', 
		'\r', '\x1A', '\xE', '\x1C', '\xF', '\x1E', '\x10', ' ', '\x11', '\"', 
		'\x12', '$', '\x13', '&', '\x14', '(', '\x15', '*', '\x16', ',', '\x17', 
		'.', '\x18', '\x30', '\x19', '\x32', '\x1A', '\x34', '\x1B', '\x36', '\x1C', 
		'\x38', '\x1D', ':', '\x1E', '<', '\x1F', '>', ' ', '@', '!', '\x42', 
		'\"', '\x4', '\x2', '\x3', '\b', '\x3', '\x2', '}', '}', '\x3', '\x2', 
		'\x32', ';', '\x4', '\x2', '$', '$', '^', '^', '\x5', '\x2', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x2', '\xE2', '\x2', '\x4', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x2', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\n', '\x3', '\x2', '\x2', '\x2', '\x3', '\f', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\xE', '\x3', '\x2', '\x2', '\x2', '\x3', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x12', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x3', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x18', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x3', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\"', '\x3', '\x2', '\x2', '\x2', '\x3', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '&', '\x3', '\x2', '\x2', '\x2', '\x3', '(', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '*', '\x3', '\x2', '\x2', '\x2', '\x3', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '.', '\x3', '\x2', '\x2', '\x2', '\x3', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x34', '\x3', '\x2', '\x2', '\x2', '\x3', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x38', '\x3', '\x2', '\x2', '\x2', '\x3', ':', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '<', '\x3', '\x2', '\x2', '\x2', '\x3', '>', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '@', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x4', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x6', 'J', '\x3', '\x2', '\x2', '\x2', '\b', 'R', '\x3', '\x2', 
		'\x2', '\x2', '\n', 'V', '\x3', '\x2', '\x2', '\x2', '\f', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x61', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x12', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x14', 'm', '\x3', '\x2', '\x2', '\x2', '\x16', 'q', '\x3', '\x2', 
		'\x2', '\x2', '\x18', 'w', '\x3', '\x2', '\x2', '\x2', '\x1A', 'z', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '}', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', ' ', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x83', '\x3', '\x2', '\x2', '\x2', '$', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x88', '\x3', '\x2', '\x2', '\x2', '(', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '*', '\xA0', '\x3', '\x2', '\x2', '\x2', ',', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', '.', '\xA5', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\x32', '\xAB', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\xAE', '\x3', '\x2', '\x2', '\x2', '\x36', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\xB4', '\x3', '\x2', '\x2', '\x2', ':', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '<', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '>', '\xBF', '\x3', '\x2', '\x2', '\x2', '@', '\xC6', '\x3', '\x2', 
		'\x2', '\x2', '\x42', '\xD5', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', 
		'\a', '}', '\x2', '\x2', '\x45', '\x46', '\a', '}', '\x2', '\x2', '\x46', 
		'G', '\a', '/', '\x2', '\x2', 'G', 'H', '\x3', '\x2', '\x2', '\x2', 'H', 
		'I', '\b', '\x2', '\x2', '\x2', 'I', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\a', '}', '\x2', '\x2', 'K', 'L', '\a', '}', '\x2', '\x2', 
		'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\b', '\x3', '\x2', '\x2', 
		'N', '\a', '\x3', '\x2', '\x2', '\x2', 'O', 'S', '\n', '\x2', '\x2', '\x2', 
		'P', 'Q', '\a', '}', '\x2', '\x2', 'Q', 'S', '\n', '\x2', '\x2', '\x2', 
		'R', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 
		'T', 'U', '\x3', '\x2', '\x2', '\x2', 'U', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'W', '\a', '/', '\x2', '\x2', 'W', 'X', '\a', '\x7F', '\x2', 
		'\x2', 'X', 'Y', '\a', '\x7F', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\b', '\x5', '\x3', '\x2', '[', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', '\x7F', '\x2', '\x2', ']', '^', '\a', '\x7F', 
		'\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', '`', '\b', '\x6', 
		'\x3', '\x2', '`', '\r', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 
		'k', '\x2', '\x2', '\x62', '\x63', '\a', 'h', '\x2', '\x2', '\x63', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 'g', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'n', '\x2', '\x2', '\x66', 'g', '\a', 'u', '\x2', '\x2', 
		'g', 'h', '\a', 'g', '\x2', '\x2', 'h', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\a', 'g', '\x2', '\x2', 'j', 'k', '\a', 'p', '\x2', '\x2', 
		'k', 'l', '\a', '\x66', '\x2', '\x2', 'l', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'n', '\a', 'h', '\x2', '\x2', 'n', 'o', '\a', 'q', '\x2', 
		'\x2', 'o', 'p', '\a', 't', '\x2', '\x2', 'p', '\x15', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', 't', '\x2', '\x2', 'r', 's', '\a', '\x63', '\x2', 
		'\x2', 's', 't', '\a', 'p', '\x2', '\x2', 't', 'u', '\a', 'i', '\x2', 
		'\x2', 'u', 'v', '\a', 'g', '\x2', '\x2', 'v', '\x17', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', 'k', '\x2', '\x2', 'x', 'y', '\a', 'p', '\x2', 
		'\x2', 'y', '\x19', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '<', '\x2', 
		'\x2', '{', '|', '\a', '?', '\x2', '\x2', '|', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '.', '\x2', '\x2', '~', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '&', '\x2', '\x2', '\x80', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\a', '\x30', '\x2', '\x2', '\x82', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', ']', '\x2', '\x2', 
		'\x84', '#', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', '_', '\x2', 
		'\x2', '\x86', '%', '\x3', '\x2', '\x2', '\x2', '\x87', '\x89', '\t', 
		'\x3', '\x2', '\x2', '\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8B', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x92', '\a', '$', '\x2', '\x2', '\x8D', 
		'\x91', '\n', '\x4', '\x2', '\x2', '\x8E', '\x8F', '\a', '^', '\x2', '\x2', 
		'\x8F', '\x91', '\v', '\x2', '\x2', '\x2', '\x90', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x92', '\x93', '\x3', '\x2', '\x2', '\x2', '\x93', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', 
		'\a', '$', '\x2', '\x2', '\x96', ')', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x98', '\a', 'v', '\x2', '\x2', '\x98', '\x99', '\a', 't', '\x2', '\x2', 
		'\x99', '\x9A', '\a', 'w', '\x2', '\x2', '\x9A', '\xA1', '\a', 'g', '\x2', 
		'\x2', '\x9B', '\x9C', '\a', 'h', '\x2', '\x2', '\x9C', '\x9D', '\a', 
		'\x63', '\x2', '\x2', '\x9D', '\x9E', '\a', 'n', '\x2', '\x2', '\x9E', 
		'\x9F', '\a', 'u', '\x2', '\x2', '\x9F', '\xA1', '\a', 'g', '\x2', '\x2', 
		'\xA0', '\x97', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '+', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', 
		'\a', 'g', '\x2', '\x2', '\xA3', '\xA4', '\a', 's', '\x2', '\x2', '\xA4', 
		'-', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', 'p', '\x2', '\x2', 
		'\xA6', '\xA7', '\a', 'g', '\x2', '\x2', '\xA7', '/', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', 'n', '\x2', '\x2', '\xA9', '\xAA', '\a', 
		'v', '\x2', '\x2', '\xAA', '\x31', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 'n', '\x2', '\x2', '\xAC', '\xAD', '\a', 'g', '\x2', '\x2', 
		'\xAD', '\x33', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', 'i', 
		'\x2', '\x2', '\xAF', '\xB0', '\a', 'v', '\x2', '\x2', '\xB0', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', 'i', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'g', '\x2', '\x2', '\xB3', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\xB4', '\xB5', '\a', '\x63', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'p', '\x2', '\x2', '\xB6', '\xB7', '\a', '\x66', '\x2', '\x2', '\xB7', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', 'q', '\x2', 
		'\x2', '\xB9', '\xBA', '\a', 't', '\x2', '\x2', '\xBA', ';', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\a', 'p', '\x2', '\x2', '\xBC', '\xBD', 
		'\a', 'q', '\x2', '\x2', '\xBD', '\xBE', '\a', 'v', '\x2', '\x2', '\xBE', 
		'=', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC3', '\t', '\x5', '\x2', '\x2', 
		'\xC0', '\xC2', '\t', '\x6', '\x2', '\x2', '\xC1', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC4', '?', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xC6', '\xC7', '\a', '\x31', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', ',', '\x2', '\x2', '\xC8', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xCB', '\v', '\x2', '\x2', '\x2', '\xCA', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\a', ',', '\x2', '\x2', '\xD0', '\xD1', '\a', 
		'\x31', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\xD3', '\b', ' ', '\x4', '\x2', '\xD3', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\xD4', '\xD6', '\t', '\a', '\x2', '\x2', '\xD5', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\b', 
		'!', '\x4', '\x2', '\xDA', '\x43', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', 
		'\x3', 'R', 'T', '\x8A', '\x90', '\x92', '\xA0', '\xC3', '\xCC', '\xD7', 
		'\x5', '\a', '\x3', '\x2', '\x6', '\x2', '\x2', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace TextTemplate
