//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TextTemplate {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GoTextTemplateParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGoTextTemplateParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate([NotNull] GoTextTemplateParser.TemplateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContent([NotNull] GoTextTemplateParser.ContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPart([NotNull] GoTextTemplateParser.PartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlaceholder([NotNull] GoTextTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.pipeline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPipeline([NotNull] GoTextTemplateParser.PipelineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] GoTextTemplateParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] GoTextTemplateParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] GoTextTemplateParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] GoTextTemplateParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] GoTextTemplateParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlock([NotNull] GoTextTemplateParser.IfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfBlock([NotNull] GoTextTemplateParser.ElseIfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.elseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseBlock([NotNull] GoTextTemplateParser.ElseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForBlock([NotNull] GoTextTemplateParser.ForBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.rangeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeBlock([NotNull] GoTextTemplateParser.RangeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.rangeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeClause([NotNull] GoTextTemplateParser.RangeClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarList([NotNull] GoTextTemplateParser.VarListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarName([NotNull] GoTextTemplateParser.VarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.open"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpen([NotNull] GoTextTemplateParser.OpenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GoTextTemplateParser.close"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClose([NotNull] GoTextTemplateParser.CloseContext context);
}
} // namespace TextTemplate
