//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TextTemplate {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class GoTextTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN_TRIM=1, OPEN=2, TEXT=3, CLOSE_TRIM=4, CLOSE=5, IF=6, ELSE=7, END=8, 
		FOR=9, RANGE=10, IN=11, COLONEQ=12, COMMA=13, DOLLAR=14, NUMBER=15, STRING=16, 
		BOOLEAN=17, EQ=18, NE=19, LT=20, LE=21, GT=22, GE=23, AND=24, OR=25, NOT=26, 
		PIPE=27, PATH=28, IDENT=29, COMMENT=30, WS=31;
	public const int
		EXPR=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "EXPR"
	};

	public static readonly string[] ruleNames = {
		"OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", "END", 
		"FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "NUMBER", "STRING", 
		"BOOLEAN", "EQ", "NE", "LT", "LE", "GT", "GE", "AND", "OR", "NOT", "PIPE", 
		"PATH", "IDENT", "COMMENT", "WS"
	};


	public GoTextTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GoTextTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{{-'", "'{{'", null, "'-}}'", "'}}'", "'if'", "'else'", "'end'", 
		"'for'", "'range'", "'in'", "':='", "','", "'$'", null, null, null, "'eq'", 
		"'ne'", "'lt'", "'le'", "'gt'", "'ge'", "'and'", "'or'", "'not'", "'|'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", 
		"END", "FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "NUMBER", "STRING", 
		"BOOLEAN", "EQ", "NE", "LT", "LE", "GT", "GE", "AND", "OR", "NOT", "PIPE", 
		"PATH", "IDENT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GoTextTemplateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GoTextTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '!', '\xEB', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x4', '\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', 
		'\x18', '\t', '\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', 
		'\x1A', '\x4', '\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', 
		'\x1D', '\t', '\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', 
		'\x1F', '\x4', ' ', '\t', ' ', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x6', '\x4', 'Q', '\n', '\x4', '\r', '\x4', '\xE', '\x4', 
		'R', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x6', '\x10', '\x81', '\n', '\x10', '\r', '\x10', '\xE', 
		'\x10', '\x82', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\a', '\x11', '\x89', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x8C', 
		'\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x99', '\n', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x5', '\x1D', '\xBB', '\n', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', '\x1D', 
		'\xC2', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\xC5', '\v', '\x1D', 
		'\x3', '\x1D', '\x6', '\x1D', '\xC8', '\n', '\x1D', '\r', '\x1D', '\xE', 
		'\x1D', '\xC9', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\xCE', '\n', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\a', '\x1E', '\xD2', '\n', '\x1E', 
		'\f', '\x1E', '\xE', '\x1E', '\xD5', '\v', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xDB', '\n', '\x1F', 
		'\f', '\x1F', '\xE', '\x1F', '\xDE', '\v', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x6', 
		' ', '\xE6', '\n', ' ', '\r', ' ', '\xE', ' ', '\xE7', '\x3', ' ', '\x3', 
		' ', '\x3', '\xDC', '\x2', '!', '\x4', '\x3', '\x6', '\x4', '\b', '\x5', 
		'\n', '\x6', '\f', '\a', '\xE', '\b', '\x10', '\t', '\x12', '\n', '\x14', 
		'\v', '\x16', '\f', '\x18', '\r', '\x1A', '\xE', '\x1C', '\xF', '\x1E', 
		'\x10', ' ', '\x11', '\"', '\x12', '$', '\x13', '&', '\x14', '(', '\x15', 
		'*', '\x16', ',', '\x17', '.', '\x18', '\x30', '\x19', '\x32', '\x1A', 
		'\x34', '\x1B', '\x36', '\x1C', '\x38', '\x1D', ':', '\x1E', '<', '\x1F', 
		'>', ' ', '@', '!', '\x4', '\x2', '\x3', '\t', '\x3', '\x2', '}', '}', 
		'\x3', '\x2', '\x32', ';', '\x4', '\x2', '$', '$', '^', '^', '\x3', '\x2', 
		'_', '_', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\xF7', '\x2', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\b', '\x3', '\x2', '\x2', '\x2', '\x3', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\f', '\x3', '\x2', '\x2', '\x2', '\x3', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x10', '\x3', '\x2', '\x2', '\x2', '\x3', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x16', '\x3', '\x2', '\x2', '\x2', '\x3', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\x3', ' ', '\x3', '\x2', '\x2', '\x2', '\x3', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '$', '\x3', '\x2', '\x2', '\x2', '\x3', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '(', '\x3', '\x2', '\x2', '\x2', '\x3', '*', '\x3', 
		'\x2', '\x2', '\x2', '\x3', ',', '\x3', '\x2', '\x2', '\x2', '\x3', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x32', '\x3', '\x2', '\x2', '\x2', '\x3', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x36', '\x3', '\x2', '\x2', '\x2', '\x3', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\x3', ':', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'<', '\x3', '\x2', '\x2', '\x2', '\x3', '>', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '@', '\x3', '\x2', '\x2', '\x2', '\x4', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x6', 'H', '\x3', '\x2', '\x2', '\x2', '\b', 'P', '\x3', '\x2', 
		'\x2', '\x2', '\n', 'T', '\x3', '\x2', '\x2', '\x2', '\f', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '_', '\x3', '\x2', '\x2', '\x2', '\x10', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x12', 'g', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'k', '\x3', '\x2', '\x2', '\x2', '\x16', 'o', '\x3', '\x2', '\x2', '\x2', 
		'\x18', 'u', '\x3', '\x2', '\x2', '\x2', '\x1A', 'x', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '{', '\x3', '\x2', '\x2', '\x2', '\x1E', '}', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\x80', '\x3', '\x2', '\x2', '\x2', '\"', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '$', '\x98', '\x3', '\x2', '\x2', '\x2', '&', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '(', '\x9D', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', ',', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '.', '\xA6', '\x3', '\x2', '\x2', '\x2', '\x30', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\xAC', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\x36', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\xB7', '\x3', '\x2', '\x2', '\x2', ':', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '<', '\xCF', '\x3', '\x2', '\x2', '\x2', '>', '\xD6', 
		'\x3', '\x2', '\x2', '\x2', '@', '\xE5', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x43', '\a', '}', '\x2', '\x2', '\x43', '\x44', '\a', '}', '\x2', '\x2', 
		'\x44', '\x45', '\a', '/', '\x2', '\x2', '\x45', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'G', '\b', '\x2', '\x2', '\x2', 'G', '\x5', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'I', '\a', '}', '\x2', '\x2', 'I', 'J', '\a', 
		'}', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\b', 
		'\x3', '\x2', '\x2', 'L', '\a', '\x3', '\x2', '\x2', '\x2', 'M', 'Q', 
		'\n', '\x2', '\x2', '\x2', 'N', 'O', '\a', '}', '\x2', '\x2', 'O', 'Q', 
		'\n', '\x2', '\x2', '\x2', 'P', 'M', '\x3', '\x2', '\x2', '\x2', 'P', 
		'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 
		'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 
		'S', '\t', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '/', '\x2', '\x2', 
		'U', 'V', '\a', '\x7F', '\x2', '\x2', 'V', 'W', '\a', '\x7F', '\x2', '\x2', 
		'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\b', '\x5', '\x3', '\x2', 
		'Y', '\v', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '\x7F', '\x2', 
		'\x2', '[', '\\', '\a', '\x7F', '\x2', '\x2', '\\', ']', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\b', '\x6', '\x3', '\x2', '^', '\r', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\a', 'k', '\x2', '\x2', '`', '\x61', '\a', 'h', 
		'\x2', '\x2', '\x61', '\xF', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', 'g', '\x2', '\x2', '\x63', '\x64', '\a', 'n', '\x2', '\x2', '\x64', 
		'\x65', '\a', 'u', '\x2', '\x2', '\x65', '\x66', '\a', 'g', '\x2', '\x2', 
		'\x66', '\x11', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 'g', '\x2', 
		'\x2', 'h', 'i', '\a', 'p', '\x2', '\x2', 'i', 'j', '\a', '\x66', '\x2', 
		'\x2', 'j', '\x13', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', 'h', '\x2', 
		'\x2', 'l', 'm', '\a', 'q', '\x2', '\x2', 'm', 'n', '\a', 't', '\x2', 
		'\x2', 'n', '\x15', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', 't', '\x2', 
		'\x2', 'p', 'q', '\a', '\x63', '\x2', '\x2', 'q', 'r', '\a', 'p', '\x2', 
		'\x2', 'r', 's', '\a', 'i', '\x2', '\x2', 's', 't', '\a', 'g', '\x2', 
		'\x2', 't', '\x17', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', 'k', '\x2', 
		'\x2', 'v', 'w', '\a', 'p', '\x2', '\x2', 'w', '\x19', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'y', '\a', '<', '\x2', '\x2', 'y', 'z', '\a', '?', '\x2', 
		'\x2', 'z', '\x1B', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '.', '\x2', 
		'\x2', '|', '\x1D', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', '&', '\x2', 
		'\x2', '~', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\t', 
		'\x3', '\x2', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x8A', '\a', '$', '\x2', '\x2', '\x85', 
		'\x89', '\n', '\x4', '\x2', '\x2', '\x86', '\x87', '\a', '^', '\x2', '\x2', 
		'\x87', '\x89', '\v', '\x2', '\x2', '\x2', '\x88', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', 
		'\a', '$', '\x2', '\x2', '\x8E', '#', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'v', '\x2', '\x2', '\x90', '\x91', '\a', 't', '\x2', '\x2', 
		'\x91', '\x92', '\a', 'w', '\x2', '\x2', '\x92', '\x99', '\a', 'g', '\x2', 
		'\x2', '\x93', '\x94', '\a', 'h', '\x2', '\x2', '\x94', '\x95', '\a', 
		'\x63', '\x2', '\x2', '\x95', '\x96', '\a', 'n', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'u', '\x2', '\x2', '\x97', '\x99', '\a', 'g', '\x2', '\x2', 
		'\x98', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x98', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '%', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', 'g', '\x2', '\x2', '\x9B', '\x9C', '\a', 's', '\x2', '\x2', '\x9C', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', 'p', '\x2', '\x2', 
		'\x9E', '\x9F', '\a', 'g', '\x2', '\x2', '\x9F', ')', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\a', 'n', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'v', '\x2', '\x2', '\xA2', '+', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', 
		'\a', 'n', '\x2', '\x2', '\xA4', '\xA5', '\a', 'g', '\x2', '\x2', '\xA5', 
		'-', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', 'i', '\x2', '\x2', 
		'\xA7', '\xA8', '\a', 'v', '\x2', '\x2', '\xA8', '/', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\a', 'i', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		'g', '\x2', '\x2', '\xAB', '\x31', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAD', '\a', '\x63', '\x2', '\x2', '\xAD', '\xAE', '\a', 'p', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', '\x66', '\x2', '\x2', '\xAF', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB1', '\a', 'q', '\x2', '\x2', '\xB1', 
		'\xB2', '\a', 't', '\x2', '\x2', '\xB2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\a', 'p', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		'q', '\x2', '\x2', '\xB5', '\xB6', '\a', 'v', '\x2', '\x2', '\xB6', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', '~', '\x2', '\x2', '\xB8', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBB', '\a', '\x30', '\x2', 
		'\x2', '\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xC7', '\x5', '<', '\x1E', '\x2', '\xBD', '\xBE', '\a', '\x30', '\x2', 
		'\x2', '\xBE', '\xC8', '\x5', '<', '\x1E', '\x2', '\xBF', '\xC3', '\a', 
		']', '\x2', '\x2', '\xC0', '\xC2', '\n', '\x5', '\x2', '\x2', '\xC1', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC8', '\a', '_', '\x2', 
		'\x2', '\xC7', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', 
		'\x30', '\x2', '\x2', '\xCC', '\xCE', '\x5', '<', '\x1E', '\x2', '\xCD', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', ';', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD3', '\t', 
		'\x6', '\x2', '\x2', '\xD0', '\xD2', '\t', '\a', '\x2', '\x2', '\xD1', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '=', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'\xD3', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\a', '\x31', '\x2', 
		'\x2', '\xD7', '\xD8', '\a', ',', '\x2', '\x2', '\xD8', '\xDC', '\x3', 
		'\x2', '\x2', '\x2', '\xD9', '\xDB', '\v', '\x2', '\x2', '\x2', '\xDA', 
		'\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDE', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', ',', '\x2', 
		'\x2', '\xE0', '\xE1', '\a', '\x31', '\x2', '\x2', '\xE1', '\xE2', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE3', '\b', '\x1F', '\x4', '\x2', '\xE3', 
		'?', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE6', '\t', '\b', '\x2', '\x2', 
		'\xE5', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\x3', '\x2', 
		'\x2', '\x2', '\xE7', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', 
		'\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', 
		'\xE9', '\xEA', '\b', ' ', '\x4', '\x2', '\xEA', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x12', '\x2', '\x3', 'P', 'R', '\x82', '\x88', '\x8A', 
		'\x98', '\xBA', '\xC3', '\xC7', '\xC9', '\xCD', '\xD3', '\xDC', '\xE7', 
		'\x5', '\a', '\x3', '\x2', '\x6', '\x2', '\x2', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace TextTemplate
