//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class GoTextTemplateParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN_TRIM=1, OPEN=2, TEXT=3, CLOSE_TRIM=4, CLOSE=5, IF=6, ELSE=7, END=8, 
		FOR=9, RANGE=10, IN=11, COLONEQ=12, COMMA=13, DOLLAR=14, NUMBER=15, STRING=16, 
		BOOLEAN=17, EQ=18, NE=19, LT=20, LE=21, GT=22, GE=23, AND=24, OR=25, NOT=26, 
		WITH=27, DEFINE=28, TEMPLATE=29, BLOCK=30, PIPE=31, DOT=32, PATH=33, IDENT=34, 
		COMMENT=35, WS=36;
	public const int
		RULE_template = 0, RULE_content = 1, RULE_part = 2, RULE_placeholder = 3, 
		RULE_pipeline = 4, RULE_command = 5, RULE_argument = 6, RULE_path = 7, 
		RULE_expr = 8, RULE_value = 9, RULE_ifBlock = 10, RULE_elseIfBlock = 11, 
		RULE_elseBlock = 12, RULE_forBlock = 13, RULE_rangeBlock = 14, RULE_withBlock = 15, 
		RULE_defineBlock = 16, RULE_templateCall = 17, RULE_blockBlock = 18, RULE_rangeClause = 19, 
		RULE_varList = 20, RULE_varName = 21, RULE_open = 22, RULE_close = 23;
	public static readonly string[] ruleNames = {
		"template", "content", "part", "placeholder", "pipeline", "command", "argument", 
		"path", "expr", "value", "ifBlock", "elseIfBlock", "elseBlock", "forBlock", 
		"rangeBlock", "withBlock", "defineBlock", "templateCall", "blockBlock", 
		"rangeClause", "varList", "varName", "open", "close"
	};

	private static readonly string[] _LiteralNames = {
		null, "'{{-'", "'{{'", null, "'-}}'", "'}}'", "'if'", "'else'", "'end'", 
		"'for'", "'range'", "'in'", "':='", "','", "'$'", null, null, null, "'eq'", 
		"'ne'", "'lt'", "'le'", "'gt'", "'ge'", "'and'", "'or'", "'not'", "'with'", 
		"'define'", "'template'", "'block'", "'|'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", 
		"END", "FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "NUMBER", "STRING", 
		"BOOLEAN", "EQ", "NE", "LT", "LE", "GT", "GE", "AND", "OR", "NOT", "WITH", 
		"DEFINE", "TEMPLATE", "BLOCK", "PIPE", "DOT", "PATH", "IDENT", "COMMENT", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GoTextTemplateParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GoTextTemplateParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GoTextTemplateParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GoTextTemplateParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class TemplateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(GoTextTemplateParser.Eof, 0); }
		public TemplateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_template; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplateContext template() {
		TemplateContext _localctx = new TemplateContext(Context, State);
		EnterRule(_localctx, 0, RULE_template);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			content();
			State = 49;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PartContext[] part() {
			return GetRuleContexts<PartContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PartContext part(int i) {
			return GetRuleContext<PartContext>(i);
		}
		public ContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_content; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContentContext content() {
		ContentContext _localctx = new ContentContext(Context, State);
		EnterRule(_localctx, 2, RULE_content);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 51;
					part();
					}
					} 
				}
				State = 56;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT() { return GetToken(GoTextTemplateParser.TEXT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PlaceholderContext placeholder() {
			return GetRuleContext<PlaceholderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfBlockContext ifBlock() {
			return GetRuleContext<IfBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ForBlockContext forBlock() {
			return GetRuleContext<ForBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RangeBlockContext rangeBlock() {
			return GetRuleContext<RangeBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WithBlockContext withBlock() {
			return GetRuleContext<WithBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DefineBlockContext defineBlock() {
			return GetRuleContext<DefineBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateCallContext templateCall() {
			return GetRuleContext<TemplateCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockBlockContext blockBlock() {
			return GetRuleContext<BlockBlockContext>(0);
		}
		public PartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_part; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PartContext part() {
		PartContext _localctx = new PartContext(Context, State);
		EnterRule(_localctx, 4, RULE_part);
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 57;
				Match(TEXT);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 58;
				placeholder();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 59;
				ifBlock();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 60;
				forBlock();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 61;
				rangeBlock();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 62;
				withBlock();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 63;
				defineBlock();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 64;
				templateCall();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 65;
				blockBlock();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlaceholderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open() {
			return GetRuleContext<OpenContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PipelineContext pipeline() {
			return GetRuleContext<PipelineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close() {
			return GetRuleContext<CloseContext>(0);
		}
		public PlaceholderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_placeholder; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlaceholder(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlaceholderContext placeholder() {
		PlaceholderContext _localctx = new PlaceholderContext(Context, State);
		EnterRule(_localctx, 6, RULE_placeholder);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			open();
			State = 69;
			pipeline();
			State = 70;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PipelineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext[] command() {
			return GetRuleContexts<CommandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command(int i) {
			return GetRuleContext<CommandContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PIPE() { return GetTokens(GoTextTemplateParser.PIPE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE(int i) {
			return GetToken(GoTextTemplateParser.PIPE, i);
		}
		public PipelineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pipeline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPipeline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PipelineContext pipeline() {
		PipelineContext _localctx = new PipelineContext(Context, State);
		EnterRule(_localctx, 8, RULE_pipeline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			command();
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PIPE) {
				{
				{
				State = 73;
				Match(PIPE);
				State = 74;
				command();
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(GoTextTemplateParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 10, RULE_command);
		int _la;
		try {
			State = 88;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80;
				path();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 81;
				Match(IDENT);
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DOLLAR) | (1L << NUMBER) | (1L << STRING) | (1L << BOOLEAN) | (1L << DOT) | (1L << PATH) | (1L << IDENT))) != 0)) {
					{
					{
					State = 82;
					argument();
					}
					}
					State = 87;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(GoTextTemplateParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(GoTextTemplateParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(GoTextTemplateParser.BOOLEAN, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 12, RULE_argument);
		try {
			State = 94;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DOLLAR:
			case DOT:
			case PATH:
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 90;
				path();
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 91;
				Match(NUMBER);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 3);
				{
				State = 92;
				Match(STRING);
				}
				break;
			case BOOLEAN:
				EnterOuterAlt(_localctx, 4);
				{
				State = 93;
				Match(BOOLEAN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(GoTextTemplateParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(GoTextTemplateParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PATH() { return GetToken(GoTextTemplateParser.PATH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOLLAR() { return GetToken(GoTextTemplateParser.DOLLAR, 0); }
		public PathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_path; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPath(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathContext path() {
		PathContext _localctx = new PathContext(Context, State);
		EnterRule(_localctx, 14, RULE_path);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOLLAR) {
				{
				State = 96;
				Match(DOLLAR);
				}
			}

			State = 99;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DOT) | (1L << PATH) | (1L << IDENT))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(GoTextTemplateParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NE() { return GetToken(GoTextTemplateParser.NE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(GoTextTemplateParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LE() { return GetToken(GoTextTemplateParser.LE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(GoTextTemplateParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GE() { return GetToken(GoTextTemplateParser.GE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(GoTextTemplateParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(GoTextTemplateParser.OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(GoTextTemplateParser.NOT, 0); }
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 16, RULE_expr);
		try {
			int _alt;
			State = 142;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DOLLAR:
			case DOT:
			case PATH:
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 101;
				path();
				}
				break;
			case EQ:
				EnterOuterAlt(_localctx, 2);
				{
				State = 102;
				Match(EQ);
				State = 103;
				value();
				State = 104;
				value();
				}
				break;
			case NE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 106;
				Match(NE);
				State = 107;
				value();
				State = 108;
				value();
				}
				break;
			case LT:
				EnterOuterAlt(_localctx, 4);
				{
				State = 110;
				Match(LT);
				State = 111;
				value();
				State = 112;
				value();
				}
				break;
			case LE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 114;
				Match(LE);
				State = 115;
				value();
				State = 116;
				value();
				}
				break;
			case GT:
				EnterOuterAlt(_localctx, 6);
				{
				State = 118;
				Match(GT);
				State = 119;
				value();
				State = 120;
				value();
				}
				break;
			case GE:
				EnterOuterAlt(_localctx, 7);
				{
				State = 122;
				Match(GE);
				State = 123;
				value();
				State = 124;
				value();
				}
				break;
			case AND:
				EnterOuterAlt(_localctx, 8);
				{
				State = 126;
				Match(AND);
				State = 127;
				expr();
				State = 129;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 128;
						expr();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 131;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case OR:
				EnterOuterAlt(_localctx, 9);
				{
				State = 133;
				Match(OR);
				State = 134;
				expr();
				State = 136;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 135;
						expr();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 138;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case NOT:
				EnterOuterAlt(_localctx, 10);
				{
				State = 140;
				Match(NOT);
				State = 141;
				expr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(GoTextTemplateParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(GoTextTemplateParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(GoTextTemplateParser.BOOLEAN, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 18, RULE_value);
		try {
			State = 148;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DOLLAR:
			case DOT:
			case PATH:
			case IDENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 144;
				path();
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 145;
				Match(NUMBER);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 3);
				{
				State = 146;
				Match(STRING);
				}
				break;
			case BOOLEAN:
				EnterOuterAlt(_localctx, 4);
				{
				State = 147;
				Match(BOOLEAN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(GoTextTemplateParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfBlockContext[] elseIfBlock() {
			return GetRuleContexts<ElseIfBlockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfBlockContext elseIfBlock(int i) {
			return GetRuleContext<ElseIfBlockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseBlockContext elseBlock() {
			return GetRuleContext<ElseBlockContext>(0);
		}
		public IfBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfBlockContext ifBlock() {
		IfBlockContext _localctx = new IfBlockContext(Context, State);
		EnterRule(_localctx, 20, RULE_ifBlock);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			open();
			State = 151;
			Match(IF);
			State = 152;
			expr();
			State = 153;
			close();
			State = 154;
			content();
			State = 158;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 155;
					elseIfBlock();
					}
					} 
				}
				State = 160;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			State = 162;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				{
				State = 161;
				elseBlock();
				}
				break;
			}
			State = 164;
			open();
			State = 165;
			Match(END);
			State = 166;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseIfBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open() {
			return GetRuleContext<OpenContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(GoTextTemplateParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(GoTextTemplateParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close() {
			return GetRuleContext<CloseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		public ElseIfBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseIfBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElseIfBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElseIfBlockContext elseIfBlock() {
		ElseIfBlockContext _localctx = new ElseIfBlockContext(Context, State);
		EnterRule(_localctx, 22, RULE_elseIfBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168;
			open();
			State = 169;
			Match(ELSE);
			State = 170;
			Match(IF);
			State = 171;
			expr();
			State = 172;
			close();
			State = 173;
			content();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open() {
			return GetRuleContext<OpenContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(GoTextTemplateParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close() {
			return GetRuleContext<CloseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		public ElseBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElseBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElseBlockContext elseBlock() {
		ElseBlockContext _localctx = new ElseBlockContext(Context, State);
		EnterRule(_localctx, 24, RULE_elseBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 175;
			open();
			State = 176;
			Match(ELSE);
			State = 177;
			close();
			State = 178;
			content();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(GoTextTemplateParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(GoTextTemplateParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(GoTextTemplateParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElseBlockContext elseBlock() {
			return GetRuleContext<ElseBlockContext>(0);
		}
		public ForBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForBlockContext forBlock() {
		ForBlockContext _localctx = new ForBlockContext(Context, State);
		EnterRule(_localctx, 26, RULE_forBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			open();
			State = 181;
			Match(FOR);
			State = 182;
			Match(IDENT);
			State = 183;
			Match(IN);
			State = 184;
			path();
			State = 185;
			close();
			State = 186;
			content();
			State = 188;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 187;
				elseBlock();
				}
				break;
			}
			State = 190;
			open();
			State = 191;
			Match(END);
			State = 192;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RangeBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RANGE() { return GetToken(GoTextTemplateParser.RANGE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RangeClauseContext rangeClause() {
			return GetRuleContext<RangeClauseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElseBlockContext elseBlock() {
			return GetRuleContext<ElseBlockContext>(0);
		}
		public RangeBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rangeBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRangeBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RangeBlockContext rangeBlock() {
		RangeBlockContext _localctx = new RangeBlockContext(Context, State);
		EnterRule(_localctx, 28, RULE_rangeBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			open();
			State = 195;
			Match(RANGE);
			State = 196;
			rangeClause();
			State = 197;
			close();
			State = 198;
			content();
			State = 200;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				State = 199;
				elseBlock();
				}
				break;
			}
			State = 202;
			open();
			State = 203;
			Match(END);
			State = 204;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WithBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITH() { return GetToken(GoTextTemplateParser.WITH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PipelineContext pipeline() {
			return GetRuleContext<PipelineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ElseBlockContext elseBlock() {
			return GetRuleContext<ElseBlockContext>(0);
		}
		public WithBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_withBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWithBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WithBlockContext withBlock() {
		WithBlockContext _localctx = new WithBlockContext(Context, State);
		EnterRule(_localctx, 30, RULE_withBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			open();
			State = 207;
			Match(WITH);
			State = 208;
			pipeline();
			State = 209;
			close();
			State = 210;
			content();
			State = 212;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				{
				State = 211;
				elseBlock();
				}
				break;
			}
			State = 214;
			open();
			State = 215;
			Match(END);
			State = 216;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefineBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEFINE() { return GetToken(GoTextTemplateParser.DEFINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(GoTextTemplateParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		public DefineBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_defineBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefineBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefineBlockContext defineBlock() {
		DefineBlockContext _localctx = new DefineBlockContext(Context, State);
		EnterRule(_localctx, 32, RULE_defineBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218;
			open();
			State = 219;
			Match(DEFINE);
			State = 220;
			Match(STRING);
			State = 221;
			close();
			State = 222;
			content();
			State = 223;
			open();
			State = 224;
			Match(END);
			State = 225;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TemplateCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open() {
			return GetRuleContext<OpenContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEMPLATE() { return GetToken(GoTextTemplateParser.TEMPLATE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(GoTextTemplateParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close() {
			return GetRuleContext<CloseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PipelineContext pipeline() {
			return GetRuleContext<PipelineContext>(0);
		}
		public TemplateCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_templateCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplateCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplateCallContext templateCall() {
		TemplateCallContext _localctx = new TemplateCallContext(Context, State);
		EnterRule(_localctx, 34, RULE_templateCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			open();
			State = 228;
			Match(TEMPLATE);
			State = 229;
			Match(STRING);
			State = 231;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DOLLAR) | (1L << DOT) | (1L << PATH) | (1L << IDENT))) != 0)) {
				{
				State = 230;
				pipeline();
				}
			}

			State = 233;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext[] open() {
			return GetRuleContexts<OpenContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpenContext open(int i) {
			return GetRuleContext<OpenContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLOCK() { return GetToken(GoTextTemplateParser.BLOCK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(GoTextTemplateParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PipelineContext pipeline() {
			return GetRuleContext<PipelineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext[] close() {
			return GetRuleContexts<CloseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CloseContext close(int i) {
			return GetRuleContext<CloseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContentContext content() {
			return GetRuleContext<ContentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(GoTextTemplateParser.END, 0); }
		public BlockBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockBlockContext blockBlock() {
		BlockBlockContext _localctx = new BlockBlockContext(Context, State);
		EnterRule(_localctx, 36, RULE_blockBlock);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 235;
			open();
			State = 236;
			Match(BLOCK);
			State = 237;
			Match(STRING);
			State = 238;
			pipeline();
			State = 239;
			close();
			State = 240;
			content();
			State = 241;
			open();
			State = 242;
			Match(END);
			State = 243;
			close();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RangeClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarListContext varList() {
			return GetRuleContext<VarListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLONEQ() { return GetToken(GoTextTemplateParser.COLONEQ, 0); }
		public RangeClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rangeClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRangeClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RangeClauseContext rangeClause() {
		RangeClauseContext _localctx = new RangeClauseContext(Context, State);
		EnterRule(_localctx, 38, RULE_rangeClause);
		try {
			State = 250;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 245;
				path();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246;
				varList();
				State = 247;
				Match(COLONEQ);
				State = 248;
				path();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarNameContext[] varName() {
			return GetRuleContexts<VarNameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarNameContext varName(int i) {
			return GetRuleContext<VarNameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(GoTextTemplateParser.COMMA, 0); }
		public VarListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VarListContext varList() {
		VarListContext _localctx = new VarListContext(Context, State);
		EnterRule(_localctx, 40, RULE_varList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 252;
			varName();
			State = 255;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COMMA) {
				{
				State = 253;
				Match(COMMA);
				State = 254;
				varName();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(GoTextTemplateParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOLLAR() { return GetToken(GoTextTemplateParser.DOLLAR, 0); }
		public VarNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VarNameContext varName() {
		VarNameContext _localctx = new VarNameContext(Context, State);
		EnterRule(_localctx, 42, RULE_varName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 258;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOLLAR) {
				{
				State = 257;
				Match(DOLLAR);
				}
			}

			State = 260;
			Match(IDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpenContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN() { return GetToken(GoTextTemplateParser.OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_TRIM() { return GetToken(GoTextTemplateParser.OPEN_TRIM, 0); }
		public OpenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_open; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpen(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpenContext open() {
		OpenContext _localctx = new OpenContext(Context, State);
		EnterRule(_localctx, 44, RULE_open);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262;
			_la = TokenStream.LA(1);
			if ( !(_la==OPEN_TRIM || _la==OPEN) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CloseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE() { return GetToken(GoTextTemplateParser.CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_TRIM() { return GetToken(GoTextTemplateParser.CLOSE_TRIM, 0); }
		public CloseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_close; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGoTextTemplateParserVisitor<TResult> typedVisitor = visitor as IGoTextTemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClose(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CloseContext close() {
		CloseContext _localctx = new CloseContext(Context, State);
		EnterRule(_localctx, 46, RULE_close);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264;
			_la = TokenStream.LA(1);
			if ( !(_la==CLOSE_TRIM || _la==CLOSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '&', '\x10D', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\a', '\x3', '\x37', '\n', '\x3', '\f', '\x3', '\xE', 
		'\x3', ':', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x5', '\x4', '\x45', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', 'N', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'Q', '\v', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'V', '\n', '\a', '\f', 
		'\a', '\xE', '\a', 'Y', '\v', '\a', '\x5', '\a', '[', '\n', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x61', '\n', 
		'\b', '\x3', '\t', '\x5', '\t', '\x64', '\n', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x6', '\n', '\x84', '\n', '\n', '\r', '\n', '\xE', '\n', 
		'\x85', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x6', '\n', '\x8B', '\n', 
		'\n', '\r', '\n', '\xE', '\n', '\x8C', '\x3', '\n', '\x3', '\n', '\x5', 
		'\n', '\x91', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x5', '\v', '\x97', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\x9F', '\n', 
		'\f', '\f', '\f', '\xE', '\f', '\xA2', '\v', '\f', '\x3', '\f', '\x5', 
		'\f', '\xA5', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\xBF', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xCB', '\n', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', '\xD7', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', 
		'\xEA', '\n', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xFD', 
		'\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', 
		'\x102', '\n', '\x16', '\x3', '\x17', '\x5', '\x17', '\x105', '\n', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x2', '\x2', '\x1A', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', '\x2', 
		'\x5', '\x3', '\x2', '\"', '$', '\x3', '\x2', '\x3', '\x4', '\x3', '\x2', 
		'\x6', '\a', '\x2', '\x11B', '\x2', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x38', '\x3', '\x2', '\x2', '\x2', '\x6', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\x46', '\x3', '\x2', '\x2', '\x2', '\n', 'J', '\x3', 
		'\x2', '\x2', '\x2', '\f', 'Z', '\x3', '\x2', '\x2', '\x2', '\xE', '`', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x63', '\x3', '\x2', '\x2', '\x2', 
		'\x12', '\x90', '\x3', '\x2', '\x2', '\x2', '\x14', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '\x98', '\x3', '\x2', '\x2', '\x2', '\x18', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\xB6', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xC4', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\xD0', '\x3', '\x2', '\x2', '\x2', '\"', '\xDC', '\x3', 
		'\x2', '\x2', '\x2', '$', '\xE5', '\x3', '\x2', '\x2', '\x2', '&', '\xED', 
		'\x3', '\x2', '\x2', '\x2', '(', '\xFC', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xFE', '\x3', '\x2', '\x2', '\x2', ',', '\x104', '\x3', '\x2', '\x2', 
		'\x2', '.', '\x108', '\x3', '\x2', '\x2', '\x2', '\x30', '\x10A', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x33', '\x5', '\x4', '\x3', '\x2', '\x33', 
		'\x34', '\a', '\x2', '\x2', '\x3', '\x34', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x37', '\x5', '\x6', '\x4', '\x2', '\x36', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x37', ':', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\x5', '\x3', '\x2', '\x2', '\x2', ':', '\x38', '\x3', 
		'\x2', '\x2', '\x2', ';', '\x45', '\a', '\x5', '\x2', '\x2', '<', '\x45', 
		'\x5', '\b', '\x5', '\x2', '=', '\x45', '\x5', '\x16', '\f', '\x2', '>', 
		'\x45', '\x5', '\x1C', '\xF', '\x2', '?', '\x45', '\x5', '\x1E', '\x10', 
		'\x2', '@', '\x45', '\x5', ' ', '\x11', '\x2', '\x41', '\x45', '\x5', 
		'\"', '\x12', '\x2', '\x42', '\x45', '\x5', '$', '\x13', '\x2', '\x43', 
		'\x45', '\x5', '&', '\x14', '\x2', '\x44', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '<', '\x3', '\x2', '\x2', '\x2', '\x44', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x44', '>', '\x3', '\x2', '\x2', '\x2', '\x44', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '@', '\x3', '\x2', '\x2', '\x2', '\x44', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'G', '\x5', '.', '\x18', '\x2', 'G', 'H', '\x5', 
		'\n', '\x6', '\x2', 'H', 'I', '\x5', '\x30', '\x19', '\x2', 'I', '\t', 
		'\x3', '\x2', '\x2', '\x2', 'J', 'O', '\x5', '\f', '\a', '\x2', 'K', 'L', 
		'\a', '!', '\x2', '\x2', 'L', 'N', '\x5', '\f', '\a', '\x2', 'M', 'K', 
		'\x3', '\x2', '\x2', '\x2', 'N', 'Q', '\x3', '\x2', '\x2', '\x2', 'O', 
		'M', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', '\x2', 
		'P', '\v', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'R', '[', '\x5', '\x10', '\t', '\x2', 'S', 'W', '\a', '$', '\x2', 
		'\x2', 'T', 'V', '\x5', '\xE', '\b', '\x2', 'U', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'Y', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', '[', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Z', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'Z', 'S', '\x3', '\x2', '\x2', '\x2', '[', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\\', '\x61', '\x5', '\x10', '\t', '\x2', ']', '\x61', '\a', 
		'\x11', '\x2', '\x2', '^', '\x61', '\a', '\x12', '\x2', '\x2', '_', '\x61', 
		'\a', '\x13', '\x2', '\x2', '`', '\\', '\x3', '\x2', '\x2', '\x2', '`', 
		']', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', '\x2', 
		'`', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x64', '\a', '\x10', '\x2', '\x2', '\x63', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\t', '\x2', '\x2', 
		'\x2', '\x66', '\x11', '\x3', '\x2', '\x2', '\x2', 'g', '\x91', '\x5', 
		'\x10', '\t', '\x2', 'h', 'i', '\a', '\x14', '\x2', '\x2', 'i', 'j', '\x5', 
		'\x14', '\v', '\x2', 'j', 'k', '\x5', '\x14', '\v', '\x2', 'k', '\x91', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '\x15', '\x2', '\x2', 'm', 
		'n', '\x5', '\x14', '\v', '\x2', 'n', 'o', '\x5', '\x14', '\v', '\x2', 
		'o', '\x91', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x16', '\x2', 
		'\x2', 'q', 'r', '\x5', '\x14', '\v', '\x2', 'r', 's', '\x5', '\x14', 
		'\v', '\x2', 's', '\x91', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 
		'\x17', '\x2', '\x2', 'u', 'v', '\x5', '\x14', '\v', '\x2', 'v', 'w', 
		'\x5', '\x14', '\v', '\x2', 'w', '\x91', '\x3', '\x2', '\x2', '\x2', 'x', 
		'y', '\a', '\x18', '\x2', '\x2', 'y', 'z', '\x5', '\x14', '\v', '\x2', 
		'z', '{', '\x5', '\x14', '\v', '\x2', '{', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\a', '\x19', '\x2', '\x2', '}', '~', '\x5', '\x14', 
		'\v', '\x2', '~', '\x7F', '\x5', '\x14', '\v', '\x2', '\x7F', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', '\x1A', '\x2', '\x2', 
		'\x81', '\x83', '\x5', '\x12', '\n', '\x2', '\x82', '\x84', '\x5', '\x12', 
		'\n', '\x2', '\x83', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x88', '\a', '\x1B', '\x2', '\x2', '\x88', '\x8A', 
		'\x5', '\x12', '\n', '\x2', '\x89', '\x8B', '\x5', '\x12', '\n', '\x2', 
		'\x8A', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x8D', '\x91', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x8F', '\a', '\x1C', '\x2', '\x2', '\x8F', '\x91', '\x5', '\x12', 
		'\n', '\x2', '\x90', 'g', '\x3', '\x2', '\x2', '\x2', '\x90', 'h', '\x3', 
		'\x2', '\x2', '\x2', '\x90', 'l', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'p', '\x3', '\x2', '\x2', '\x2', '\x90', 't', '\x3', '\x2', '\x2', '\x2', 
		'\x90', 'x', '\x3', '\x2', '\x2', '\x2', '\x90', '|', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x80', '\x3', '\x2', '\x2', '\x2', '\x90', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x92', '\x97', '\x5', '\x10', '\t', 
		'\x2', '\x93', '\x97', '\a', '\x11', '\x2', '\x2', '\x94', '\x97', '\a', 
		'\x12', '\x2', '\x2', '\x95', '\x97', '\a', '\x13', '\x2', '\x2', '\x96', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x96', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x15', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x99', '\x5', '.', '\x18', '\x2', '\x99', '\x9A', '\a', '\b', '\x2', 
		'\x2', '\x9A', '\x9B', '\x5', '\x12', '\n', '\x2', '\x9B', '\x9C', '\x5', 
		'\x30', '\x19', '\x2', '\x9C', '\xA0', '\x5', '\x4', '\x3', '\x2', '\x9D', 
		'\x9F', '\x5', '\x18', '\r', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA5', '\x5', '\x1A', '\xE', '\x2', '\xA4', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x5', '.', '\x18', 
		'\x2', '\xA7', '\xA8', '\a', '\n', '\x2', '\x2', '\xA8', '\xA9', '\x5', 
		'\x30', '\x19', '\x2', '\xA9', '\x17', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\x5', '.', '\x18', '\x2', '\xAB', '\xAC', '\a', '\t', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', '\b', '\x2', '\x2', '\xAD', '\xAE', '\x5', 
		'\x12', '\n', '\x2', '\xAE', '\xAF', '\x5', '\x30', '\x19', '\x2', '\xAF', 
		'\xB0', '\x5', '\x4', '\x3', '\x2', '\xB0', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\x5', '.', '\x18', '\x2', '\xB2', '\xB3', '\a', 
		'\t', '\x2', '\x2', '\xB3', '\xB4', '\x5', '\x30', '\x19', '\x2', '\xB4', 
		'\xB5', '\x5', '\x4', '\x3', '\x2', '\xB5', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB7', '\x5', '.', '\x18', '\x2', '\xB7', '\xB8', '\a', 
		'\v', '\x2', '\x2', '\xB8', '\xB9', '\a', '$', '\x2', '\x2', '\xB9', '\xBA', 
		'\a', '\r', '\x2', '\x2', '\xBA', '\xBB', '\x5', '\x10', '\t', '\x2', 
		'\xBB', '\xBC', '\x5', '\x30', '\x19', '\x2', '\xBC', '\xBE', '\x5', '\x4', 
		'\x3', '\x2', '\xBD', '\xBF', '\x5', '\x1A', '\xE', '\x2', '\xBE', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', 
		'\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x5', '.', 
		'\x18', '\x2', '\xC1', '\xC2', '\a', '\n', '\x2', '\x2', '\xC2', '\xC3', 
		'\x5', '\x30', '\x19', '\x2', '\xC3', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\xC4', '\xC5', '\x5', '.', '\x18', '\x2', '\xC5', '\xC6', '\a', '\f', 
		'\x2', '\x2', '\xC6', '\xC7', '\x5', '(', '\x15', '\x2', '\xC7', '\xC8', 
		'\x5', '\x30', '\x19', '\x2', '\xC8', '\xCA', '\x5', '\x4', '\x3', '\x2', 
		'\xC9', '\xCB', '\x5', '\x1A', '\xE', '\x2', '\xCA', '\xC9', '\x3', '\x2', 
		'\x2', '\x2', '\xCA', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', 
		'\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x5', '.', '\x18', '\x2', 
		'\xCD', '\xCE', '\a', '\n', '\x2', '\x2', '\xCE', '\xCF', '\x5', '\x30', 
		'\x19', '\x2', '\xCF', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', 
		'\x5', '.', '\x18', '\x2', '\xD1', '\xD2', '\a', '\x1D', '\x2', '\x2', 
		'\xD2', '\xD3', '\x5', '\n', '\x6', '\x2', '\xD3', '\xD4', '\x5', '\x30', 
		'\x19', '\x2', '\xD4', '\xD6', '\x5', '\x4', '\x3', '\x2', '\xD5', '\xD7', 
		'\x5', '\x1A', '\xE', '\x2', '\xD6', '\xD5', '\x3', '\x2', '\x2', '\x2', 
		'\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xD9', '\x5', '.', '\x18', '\x2', '\xD9', '\xDA', 
		'\a', '\n', '\x2', '\x2', '\xDA', '\xDB', '\x5', '\x30', '\x19', '\x2', 
		'\xDB', '!', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\x5', '.', '\x18', 
		'\x2', '\xDD', '\xDE', '\a', '\x1E', '\x2', '\x2', '\xDE', '\xDF', '\a', 
		'\x12', '\x2', '\x2', '\xDF', '\xE0', '\x5', '\x30', '\x19', '\x2', '\xE0', 
		'\xE1', '\x5', '\x4', '\x3', '\x2', '\xE1', '\xE2', '\x5', '.', '\x18', 
		'\x2', '\xE2', '\xE3', '\a', '\n', '\x2', '\x2', '\xE3', '\xE4', '\x5', 
		'\x30', '\x19', '\x2', '\xE4', '#', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE6', '\x5', '.', '\x18', '\x2', '\xE6', '\xE7', '\a', '\x1F', '\x2', 
		'\x2', '\xE7', '\xE9', '\a', '\x12', '\x2', '\x2', '\xE8', '\xEA', '\x5', 
		'\n', '\x6', '\x2', '\xE9', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', '\xEC', '\x5', '\x30', '\x19', '\x2', '\xEC', '%', '\x3', 
		'\x2', '\x2', '\x2', '\xED', '\xEE', '\x5', '.', '\x18', '\x2', '\xEE', 
		'\xEF', '\a', ' ', '\x2', '\x2', '\xEF', '\xF0', '\a', '\x12', '\x2', 
		'\x2', '\xF0', '\xF1', '\x5', '\n', '\x6', '\x2', '\xF1', '\xF2', '\x5', 
		'\x30', '\x19', '\x2', '\xF2', '\xF3', '\x5', '\x4', '\x3', '\x2', '\xF3', 
		'\xF4', '\x5', '.', '\x18', '\x2', '\xF4', '\xF5', '\a', '\n', '\x2', 
		'\x2', '\xF5', '\xF6', '\x5', '\x30', '\x19', '\x2', '\xF6', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xFD', '\x5', '\x10', '\t', '\x2', '\xF8', 
		'\xF9', '\x5', '*', '\x16', '\x2', '\xF9', '\xFA', '\a', '\xE', '\x2', 
		'\x2', '\xFA', '\xFB', '\x5', '\x10', '\t', '\x2', '\xFB', '\xFD', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xFC', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', '\xFD', ')', '\x3', '\x2', '\x2', 
		'\x2', '\xFE', '\x101', '\x5', ',', '\x17', '\x2', '\xFF', '\x100', '\a', 
		'\xF', '\x2', '\x2', '\x100', '\x102', '\x5', ',', '\x17', '\x2', '\x101', 
		'\xFF', '\x3', '\x2', '\x2', '\x2', '\x101', '\x102', '\x3', '\x2', '\x2', 
		'\x2', '\x102', '+', '\x3', '\x2', '\x2', '\x2', '\x103', '\x105', '\a', 
		'\x10', '\x2', '\x2', '\x104', '\x103', '\x3', '\x2', '\x2', '\x2', '\x104', 
		'\x105', '\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\x3', '\x2', '\x2', 
		'\x2', '\x106', '\x107', '\a', '$', '\x2', '\x2', '\x107', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x108', '\x109', '\t', '\x3', '\x2', '\x2', '\x109', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x10A', '\x10B', '\t', '\x4', '\x2', 
		'\x2', '\x10B', '\x31', '\x3', '\x2', '\x2', '\x2', '\x16', '\x38', '\x44', 
		'O', 'W', 'Z', '`', '\x63', '\x85', '\x8C', '\x90', '\x96', '\xA0', '\xA4', 
		'\xBE', '\xCA', '\xD6', '\xE9', '\xFC', '\x101', '\x104',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
