//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TextTemplate {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GoTextTemplateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IGoTextTemplateParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] GoTextTemplateParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] GoTextTemplateParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] GoTextTemplateParser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] GoTextTemplateParser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPart([NotNull] GoTextTemplateParser.PartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPart([NotNull] GoTextTemplateParser.PartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlaceholder([NotNull] GoTextTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlaceholder([NotNull] GoTextTemplateParser.PlaceholderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.pipeline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPipeline([NotNull] GoTextTemplateParser.PipelineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.pipeline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPipeline([NotNull] GoTextTemplateParser.PipelineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] GoTextTemplateParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] GoTextTemplateParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] GoTextTemplateParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] GoTextTemplateParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] GoTextTemplateParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] GoTextTemplateParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] GoTextTemplateParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] GoTextTemplateParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] GoTextTemplateParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] GoTextTemplateParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] GoTextTemplateParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] GoTextTemplateParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfBlock([NotNull] GoTextTemplateParser.ElseIfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfBlock([NotNull] GoTextTemplateParser.ElseIfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.elseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseBlock([NotNull] GoTextTemplateParser.ElseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.elseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseBlock([NotNull] GoTextTemplateParser.ElseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForBlock([NotNull] GoTextTemplateParser.ForBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForBlock([NotNull] GoTextTemplateParser.ForBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.rangeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeBlock([NotNull] GoTextTemplateParser.RangeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.rangeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeBlock([NotNull] GoTextTemplateParser.RangeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.rangeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeClause([NotNull] GoTextTemplateParser.RangeClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.rangeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeClause([NotNull] GoTextTemplateParser.RangeClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarList([NotNull] GoTextTemplateParser.VarListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarList([NotNull] GoTextTemplateParser.VarListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] GoTextTemplateParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] GoTextTemplateParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.open"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpen([NotNull] GoTextTemplateParser.OpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.open"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpen([NotNull] GoTextTemplateParser.OpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoTextTemplateParser.close"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClose([NotNull] GoTextTemplateParser.CloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoTextTemplateParser.close"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClose([NotNull] GoTextTemplateParser.CloseContext context);
}
} // namespace TextTemplate
