//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTextTemplateLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class GoTextTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN_TRIM=1, OPEN=2, TEXT=3, CLOSE_TRIM=4, CLOSE=5, IF=6, ELSE=7, END=8, 
		FOR=9, RANGE=10, IN=11, COLONEQ=12, COMMA=13, DOLLAR=14, DOT=15, LBRACK=16, 
		RBRACK=17, NUMBER=18, STRING=19, BOOLEAN=20, EQ=21, IDENT=22, COMMENT=23, 
		WS=24;
	public const int
		EXPR=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "EXPR"
	};

	public static readonly string[] ruleNames = {
		"OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", "END", 
		"FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "DOT", "LBRACK", "RBRACK", 
		"NUMBER", "STRING", "BOOLEAN", "EQ", "IDENT", "COMMENT", "WS"
	};


	public GoTextTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GoTextTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{{-'", "'{{'", null, "'-}}'", "'}}'", "'if'", "'else'", "'end'", 
		"'for'", "'range'", "'in'", "':='", "','", "'$'", "'.'", "'['", "']'", 
		null, null, null, "'eq'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN_TRIM", "OPEN", "TEXT", "CLOSE_TRIM", "CLOSE", "IF", "ELSE", 
		"END", "FOR", "RANGE", "IN", "COLONEQ", "COMMA", "DOLLAR", "DOT", "LBRACK", 
		"RBRACK", "NUMBER", "STRING", "BOOLEAN", "EQ", "IDENT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GoTextTemplateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GoTextTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xB1', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x4', '\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', 
		'\x18', '\t', '\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x6', '\x4', '\x43', '\n', '\x4', 
		'\r', '\x4', '\xE', '\x4', '\x44', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x6', 
		'\x13', 'y', '\n', '\x13', '\r', '\x13', '\xE', '\x13', 'z', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\x81', '\n', 
		'\x14', '\f', '\x14', '\xE', '\x14', '\x84', '\v', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x5', '\x15', '\x91', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\x98', '\n', '\x17', 
		'\f', '\x17', '\xE', '\x17', '\x9B', '\v', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\xA1', '\n', '\x18', 
		'\f', '\x18', '\xE', '\x18', '\xA4', '\v', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x6', 
		'\x19', '\xAC', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xAD', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\xA2', '\x2', '\x1A', '\x4', '\x3', '\x6', 
		'\x4', '\b', '\x5', '\n', '\x6', '\f', '\a', '\xE', '\b', '\x10', '\t', 
		'\x12', '\n', '\x14', '\v', '\x16', '\f', '\x18', '\r', '\x1A', '\xE', 
		'\x1C', '\xF', '\x1E', '\x10', ' ', '\x11', '\"', '\x12', '$', '\x13', 
		'&', '\x14', '(', '\x15', '*', '\x16', ',', '\x17', '.', '\x18', '\x30', 
		'\x19', '\x32', '\x1A', '\x4', '\x2', '\x3', '\b', '\x3', '\x2', '}', 
		'}', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '$', '$', '^', '^', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x2', '\xB8', '\x2', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x6', '\x3', '\x2', '\x2', '\x2', '\x2', '\b', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\n', '\x3', '\x2', '\x2', '\x2', '\x3', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\xE', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x3', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x14', '\x3', '\x2', '\x2', '\x2', '\x3', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x18', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x3', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\"', '\x3', '\x2', '\x2', '\x2', '\x3', '$', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '&', '\x3', '\x2', '\x2', '\x2', '\x3', '(', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '*', '\x3', '\x2', '\x2', '\x2', '\x3', 
		',', '\x3', '\x2', '\x2', '\x2', '\x3', '.', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x30', '\x3', '\x2', '\x2', '\x2', '\x3', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x4', '\x34', '\x3', '\x2', '\x2', '\x2', '\x6', ':', '\x3', 
		'\x2', '\x2', '\x2', '\b', '\x42', '\x3', '\x2', '\x2', '\x2', '\n', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\f', 'L', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'Q', '\x3', '\x2', '\x2', '\x2', '\x10', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x12', 'Y', '\x3', '\x2', '\x2', '\x2', '\x14', ']', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x61', '\x3', '\x2', '\x2', '\x2', '\x18', 'g', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', 'j', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'm', '\x3', '\x2', '\x2', '\x2', '\x1E', 'o', '\x3', '\x2', '\x2', '\x2', 
		' ', 'q', '\x3', '\x2', '\x2', '\x2', '\"', 's', '\x3', '\x2', '\x2', 
		'\x2', '$', 'u', '\x3', '\x2', '\x2', '\x2', '&', 'x', '\x3', '\x2', '\x2', 
		'\x2', '(', '|', '\x3', '\x2', '\x2', '\x2', '*', '\x90', '\x3', '\x2', 
		'\x2', '\x2', ',', '\x92', '\x3', '\x2', '\x2', '\x2', '.', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', '}', '\x2', 
		'\x2', '\x35', '\x36', '\a', '}', '\x2', '\x2', '\x36', '\x37', '\a', 
		'/', '\x2', '\x2', '\x37', '\x38', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x39', '\b', '\x2', '\x2', '\x2', '\x39', '\x5', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\a', '}', '\x2', '\x2', ';', '<', '\a', '}', '\x2', 
		'\x2', '<', '=', '\x3', '\x2', '\x2', '\x2', '=', '>', '\b', '\x3', '\x2', 
		'\x2', '>', '\a', '\x3', '\x2', '\x2', '\x2', '?', '\x43', '\n', '\x2', 
		'\x2', '\x2', '@', '\x41', '\a', '}', '\x2', '\x2', '\x41', '\x43', '\n', 
		'\x2', '\x2', '\x2', '\x42', '?', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'@', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\t', '\x3', '\x2', '\x2', '\x2', '\x46', 
		'G', '\a', '/', '\x2', '\x2', 'G', 'H', '\a', '\x7F', '\x2', '\x2', 'H', 
		'I', '\a', '\x7F', '\x2', '\x2', 'I', 'J', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\b', '\x5', '\x3', '\x2', 'K', '\v', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\a', '\x7F', '\x2', '\x2', 'M', 'N', '\a', '\x7F', '\x2', '\x2', 
		'N', 'O', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\b', '\x6', '\x3', '\x2', 
		'P', '\r', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', 'k', '\x2', '\x2', 
		'R', 'S', '\a', 'h', '\x2', '\x2', 'S', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'T', 'U', '\a', 'g', '\x2', '\x2', 'U', 'V', '\a', 'n', '\x2', '\x2', 
		'V', 'W', '\a', 'u', '\x2', '\x2', 'W', 'X', '\a', 'g', '\x2', '\x2', 
		'X', '\x11', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', 'g', '\x2', '\x2', 
		'Z', '[', '\a', 'p', '\x2', '\x2', '[', '\\', '\a', '\x66', '\x2', '\x2', 
		'\\', '\x13', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', 'h', '\x2', 
		'\x2', '^', '_', '\a', 'q', '\x2', '\x2', '_', '`', '\a', 't', '\x2', 
		'\x2', '`', '\x15', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 
		't', '\x2', '\x2', '\x62', '\x63', '\a', '\x63', '\x2', '\x2', '\x63', 
		'\x64', '\a', 'p', '\x2', '\x2', '\x64', '\x65', '\a', 'i', '\x2', '\x2', 
		'\x65', '\x66', '\a', 'g', '\x2', '\x2', '\x66', '\x17', '\x3', '\x2', 
		'\x2', '\x2', 'g', 'h', '\a', 'k', '\x2', '\x2', 'h', 'i', '\a', 'p', 
		'\x2', '\x2', 'i', '\x19', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', 
		'<', '\x2', '\x2', 'k', 'l', '\a', '?', '\x2', '\x2', 'l', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'n', '\a', '.', '\x2', '\x2', 'n', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\a', '&', '\x2', '\x2', 'p', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'r', '\a', '\x30', '\x2', '\x2', 'r', '!', '\x3', 
		'\x2', '\x2', '\x2', 's', 't', '\a', ']', '\x2', '\x2', 't', '#', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\a', '_', '\x2', '\x2', 'v', '%', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'y', '\t', '\x3', '\x2', '\x2', 'x', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', '\'', 
		'\x3', '\x2', '\x2', '\x2', '|', '\x82', '\a', '$', '\x2', '\x2', '}', 
		'\x81', '\n', '\x4', '\x2', '\x2', '~', '\x7F', '\a', '^', '\x2', '\x2', 
		'\x7F', '\x81', '\v', '\x2', '\x2', '\x2', '\x80', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x81', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', 
		'\a', '$', '\x2', '\x2', '\x86', ')', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x88', '\a', 'v', '\x2', '\x2', '\x88', '\x89', '\a', 't', '\x2', '\x2', 
		'\x89', '\x8A', '\a', 'w', '\x2', '\x2', '\x8A', '\x91', '\a', 'g', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 'h', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'\x63', '\x2', '\x2', '\x8D', '\x8E', '\a', 'n', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', 'u', '\x2', '\x2', '\x8F', '\x91', '\a', 'g', '\x2', '\x2', 
		'\x90', '\x87', '\x3', '\x2', '\x2', '\x2', '\x90', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '+', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', 
		'\a', 'g', '\x2', '\x2', '\x93', '\x94', '\a', 's', '\x2', '\x2', '\x94', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x95', '\x99', '\t', '\x5', '\x2', '\x2', 
		'\x96', '\x98', '\t', '\x6', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x9A', '/', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x9D', '\a', '\x31', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', ',', '\x2', '\x2', '\x9E', '\xA2', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA1', '\v', '\x2', '\x2', '\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA6', '\a', ',', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'\x31', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA9', '\b', '\x18', '\x4', '\x2', '\xA9', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAC', '\t', '\a', '\x2', '\x2', '\xAB', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\b', 
		'\x19', '\x4', '\x2', '\xB0', '\x33', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\x2', '\x3', '\x42', '\x44', 'z', '\x80', '\x82', '\x90', '\x99', '\xA2', 
		'\xAD', '\x5', '\a', '\x3', '\x2', '\x6', '\x2', '\x2', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
